### ISSUE TITLE
Guru Creation Request: PrimeFaces

### ISSUE THREAD

**Issue by melloware** [getanteon/gurubase#1]
**GitHub:** https://github.com/primefaces/primefaces
**Maintainer:** yes

![image](https://github.com/user-attachments/assets/dc180bd1-0b95-4e18-8491-460224433a69)

**Comment by kursataktas** [comment]
Hey @melloware 

Do you have a Gurubase account that I can assign the PrimeFaces Guru once I create it?

**Comment by melloware** [comment]
I just created a gurubase account with my GitHub melloware account.
