### ISSUE TITLE
Guru Claim Request: Nhost Guru

### ISSUE THREAD

**Issue by dbarrosop** [getanteon/gurubase#10]
**Gurubase Username:** 

"David Barroso" (registered with github so it should be associated with this handle)

**Guru Link:** 

https://gurubase.io/g/nhost

**Proof of Maintainership:** 

https://github.com/nhost/nhost/releases/tag/release-20241101

**Comment by kursataktas** [comment]
Hi @dbarrosop 

I’ve assigned it to your Gurubase account. You can find it in the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
