### ISSUE TITLE
Guru Claim Request: PMD

### ISSUE THREAD

**Issue by adangel** [getanteon/gurubase#11]
**Gurubase Username:** Andreas Dangel

**Guru Link:** https://gurubase.io/g/pmd

**Proof of Maintainership:** https://github.com/pmd/pmd/pull/5337

**Comment by kursataktas** [comment]
Hi @adangel 

I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).

**Comment by adangel** [comment]
Thanks!
