### ISSUE TITLE
Guru Claim Request: Navidrome

### ISSUE THREAD

**Issue by deluan** [getanteon/gurubase#13]
**Gurubase Username:** 
"Deluan Quintão"

**Guru Link:** 
https://gurubase.io/g/navidrome

**Proof of Maintainership:** 
https://github.com/navidrome/navidrome/pull/3491

**Comment by kursataktas** [comment]
Hey @deluan 
I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
