### ISSUE TITLE
Guru Creation Request: https://github.com/home-assistant/core

### ISSUE THREAD

**Issue by ghazlewood** [getanteon/gurubase#15]
**GitHub Repo URL:**
https://github.com/home-assistant/core

**Documentation URL:** 
https://home-assistant.io/docs/

**Are you a maintainer of this tool (Y/N):**
N

**Comment by kursataktas** [comment]
Hey @ghazlewood 

[Home Assistant Guru](https://gurubase.io/g/home-assistant) is ready to use. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
