### ISSUE TITLE
Guru Claim Request: quarkus

### ISSUE THREAD

**Issue by phillip-kruger** [getanteon/gurubase#16]
**Gurubase Username:** 
Phillip Krüger

**Guru Link:** 
https://gurubase.io/g/quarkus

**Proof of Maintainership:** 
https://github.com/quarkusio/quarkus/pull/45076

**Comment by kursataktas** [comment]
Hey @phillip-kruger 
I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).

**Comment by phillip-kruger** [comment]
Awesome ! Thanks !
