### ISSUE TITLE
Guru Claim Request: Quarkus

### ISSUE THREAD

**Issue by maxandersen** [getanteon/gurubase#17]
**Gurubase Username:** 
quarkusio@gmail.com

**Guru Link:** 
[](https://gurubase.io/g/quarkus)

**Proof of Maintainership:** 
I'm admin and co-lead of quarkus - pr's merged by me here
https://github.com/quarkusio/quarkus/pulls?q=author%3Amaxandersen

account used for gurubase is using our quarkus bot/account so if/when get hit by a bus admin team can get access :)

**Comment by kursataktas** [comment]
I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
