### ISSUE TITLE
Guru Claim Request: NGXS

### ISSUE THREAD

**Issue by markwhitfeld** [getanteon/gurubase#21]
**Gurubase Username:** 
Mark Whitfeld

**Guru Link:** 
https://gurubase.io/g/ngxs

**Proof of Maintainership:** 
https://github.com/ngxs/store/pull/2250 😉

**Comment by kursataktas** [comment]
Hey @markwhitfeld 

I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
