### ISSUE TITLE
Guru Claim Request: HestiaCP

### ISSUE THREAD

**Issue by jaapmarcus** [getanteon/gurubase#22]
**Gurubase Username:** 
Jaap Marcus

**Guru Link:** 
https://gurubase.io/g/hestia

**Proof of Maintainership:** 
https://github.com/hestiacp/hestiacp/pull/4628

**Comment by kursataktas** [comment]
Hey @jaapmarcus 

I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
