### ISSUE TITLE
Guru Claim Request: Sandboxie

### ISSUE THREAD

**Issue by DavidXanatos** [getanteon/gurubase#23]
**Gurubase Username:** 
David Xanatos

**Guru Link:** 
https://gurubase.io/g/sandboxie

**Proof of Maintainership:** 
https://github.com/sandboxie-plus/Sandboxie/commit/ece1bfa733383eb59f7201d7f15774e85f436f48

**Comment by kursataktas** [comment]
Hey @DavidXanatos 

I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
