### ISSUE TITLE
Guru Claim Request (trame+vtk)

### ISSUE THREAD

**Issue by jourdain** [getanteon/gurubase#3]
__Guru__: https://gurubase.io/g/trame

<img width="455" alt="Screenshot 2024-11-25 at 15 10 33" src="https://github.com/user-attachments/assets/07951c7f-910d-413e-b136-ed6db9ba408c">

__Guru__: https://gurubase.io/g/vtk

<img width="455" alt="Screenshot 2024-11-25 at 15 11 03" src="https://github.com/user-attachments/assets/557b40cf-0be3-4e7a-8b83-a8c89140bf83">

**Comment by kursataktas** [comment]
Done! 🚀

**Comment by kursataktas** [comment]
I'm closing this one. Feel free to reach out here or on Discord if you need any help
