### ISSUE TITLE
Guru Claim Request

### ISSUE THREAD

**Issue by Tao-VanJS** [getanteon/gurubase#4]
Link to guru: https://gurubase.io/g/vanjs
Gurubase username: tao@vanjs.org
Proof of maintainer-ship: The code repo https://github.com/vanjs-org/van, where I contributed most of the commits

**Comment by kursataktas** [comment]
I’ve assigned it to your Gurubase account. You can find it in the 'My Gurus' section. Let me know if you need any help.
