### ISSUE TITLE
Claim request

### ISSUE THREAD

**Issue by ddnexus** [getanteon/gurubase#5]
https://gurubase.io/g/pagy
dd.nexus@gmail.com 
benkoshy@hotmail.com

![image](https://github.com/user-attachments/assets/d9ec8dfa-4810-4768-8508-ec66cdb62bc6)

**Comment by kursataktas** [comment]
Unfortunately, I can only assign it to one account, as Gurubase doesn’t support multi-account maintainership yet. Once that feature is available, I can add the other account. For now, which account would you prefer to add as the maintainer?

**Comment by ddnexus** [comment]
dd.nexus@gmail.com

**Comment by kursataktas** [comment]
I’ve assigned it to your Gurubase account. You can find it in the 'My Gurus' section. Please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).

I'm not closing this issue, as I'll update this thread once we support multi-account maintainership.
