### ISSUE TITLE
Guru Claim Request: FastEndpoints

### ISSUE THREAD

**Issue by dj-nitehawk** [getanteon/gurubase#6]
**Gurubase Username:** 
[Dĵ ΝιΓΞΗΛψΚ](https://github.com/dj-nitehawk)

**Guru Link:** 
https://gurubase.io/g/fastendpoints

**Proof of Maintainership:** 
https://github.com/FastEndpoints/FastEndpoints/graphs/contributors

**Comment by kursataktas** [comment]
I’ve assigned it to your Gurubase account. You can find it in the 'My Gurus' section. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
