### ISSUE TITLE
Guru Claim Request: Fomantic-UI

### ISSUE THREAD

**Issue by lubber-de** [getanteon/gurubase#8]
**Gurubase Username:** 
Marco "Lubber" Wienkoop

**Guru Link:** 
https://gurubase.io/g/fomantic-ui

**Proof of Maintainership:** 
Approved / Merged / created PRs (check any ;))
https://github.com/fomantic/Fomantic-UI/issues?q=sort%3Aupdated-desc+is%3Amerged+author%3Alubber-de

Otherwise take a look at https://github.com/lubber-de to check my fomantic org membership

**Comment by kursataktas** [comment]
I’ve assigned it to your Gurubase account. You can find it in the 'My Gurus' section. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
