### ISSUE TITLE
Guru Claim Request: Elsa

### ISSUE THREAD

**Issue by sfmskywalker** [getanteon/gurubase#9]
**Gurubase Username:** 
Sipke Schoorstra

**Guru Link:** 
[](https://gurubase.io/g/elsa)

**Proof of Maintainership:** 
https://github.com/elsa-workflows/elsa-core/commit/8502165dcca709daab57bc1f64b890f72f4b5fc5

**Comment by kursataktas** [comment]
Hey @sfmskywalker 

I’ve assigned it to your Gurubase account. You can find it in the 'My Gurus' section. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).

**Comment by sfmskywalker** [comment]
Many thanks! 🙏
